language: node_js
sudo: required
node_js:
  - 12.16.3
cache:
  directories: 
    - node_modules
branches:
  only:
  - src
before_install:
  - npm install -g hexo-cli
install:
  - npm install
script:
  - rm -rf public
  - hexo clean
  - hexo generate
  - npx gulp
after_script:
  - git config user.name "Jacksonlike"
  - git config user.email "jacksonlike290@163.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
addons:
  ssh_known_hosts: 106.52.147.227
