language: node_js
sudo: required
node_js:
- 12.16.3
cache:
  directories: 
    - node_modules
branches:
  only:
  - src
before_install:
- openssl aes-256-cbc -K $encrypted_416b9de205a4_key -iv $encrypted_416b9de205a4_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- npm install -g hexo-cli
install:
- npm install
script:
- rm -rf public
- hexo clean
- hexo generate
- npx gulp
after_script:
- sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
- hexo deploy
